# Generated by Django 2.2.6 on 2020-06-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('company', models.CharField(max_length=300)),
                ('insurance_type', models.CharField(max_length=150)),
            ],
        ),
    ]
